### PR TITLE
Updated var to const in Arrays problem/solution folders

### PR DESCRIPTION
**Pull request by MatthewStoddart**
I updated `var` in the Arrays problem folder and Arrays solution folder to `const`.

Reference #229

### CODE REVIEW

**Comment by AryanJ-NYC** [comment]
@MatthewStoddart why did you close this? It is yet to be merged into `es6`.

**Comment by MatthewStoddart** [comment]
Sorry it was an accident.

**Comment by ledsun** [comment]
I think that this PR is duplicated with #245.

**Comment by MatthewStoddart** [comment]
@AryanJ-NYC Should I close this since #245 has been merged?

**Comment by AryanJ-NYC** [comment]
Sure.

**Pull request closed without merging**
