### PR TITLE
add workshopper-adventure-test

### PR DESCRIPTION
**Pull request by ccarruitero**
This PR is an attempt to add `workshopper-adventure-test` for verify solutions, like commented in #281.

This is using feature branches for workshopper/workshopper-adventure-test#33 and workshopper/workshopper-adventure#107, since that changes are needed for load exercises correctly. But would be great if someone can help review that PRs in order to get merged.

### CODE REVIEW

**Comment by ledsun** [comment]
I think there are two options.

1. Wait for a new version of workshopper-adventure-test.
2. Change `workshopper-adventure` and `workshopper-adventure-test` dependency to github (implement this pull request).

It is better to choose the former.
The latter requires a git command in the javascripting execution environment.

I will make sure that the `ccarruitero:workshopper-test` branch works fine in my environment.

**Comment by ledsun** [comment]
In https://github.com/workshopper/javascripting/commit/aeaa4ae5f7a6e1a33d757d6933f873489792bab1 , I tried to adjust the javascripting directory structure to workshopper-adventure-test.
With this fix, we don't have to wait for the workshopper-adventure and workshopper-adventure-test to be fixed.

Do you think this is a good way?

**Comment by ccarruitero** [comment]
Well, it's the kind of changes I try to avoid with the PR.

Like you mention, a new version for `workshopper-adventure` and `workshopper-adventure-test` will be the best. I hope the PRs in that repos would be reviewed and merged with next weeks.

If you can, leave a comment in workshopper/workshopper-adventure-test#33 and workshopper/workshopper-adventure#107

**Comment by ccarruitero** [comment]
@ledsun we finally get a new version of `workshopper-adventure-test`.
I updated the PR. Take a look when you have a chance.

**Comment by ledsun** [comment]
Great work!

**Pull request merged**
