### PR TITLE
changes var to let in variables

### PR DESCRIPTION
**Pull request by alexey-pd**
contribution to issue https://github.com/workshopper/javascripting/issues/229

### CODE REVIEW

**Comment by AnshulMalik** [comment]
Okay, this one will be interesting, so since this is variables exercise itself.
Earlier we had just `var`, now we have `let` and `const`, we should update this exercise to educate how they work and how they are different.
We can have this change in this PR itself or another one as you like @a0viedo :)

**Comment by alexey-pd** [comment]
Sounds well, we use this workshopper every meetup of nodeschool/spb community and can teach es6 tasks to our students
@AnshulMalik @a0viedo thanks for javascripting 👍

**Comment by AnshulMalik** [comment]
Yeah, it's a nice place to learn. You can add those changes here or in another PR @alexey-pd

**Comment by a0viedo** [comment]
if someone else would like to review the PR that would be amazing @workshopper/core

**Pull request merged**
