### PR TITLE
chore: add travis config

### PR DESCRIPTION
**Pull request by ccarruitero**
Aside config file, we need to activate repository in travis

### CODE REVIEW

**Comment by itzsaga** [comment]
I think we should add 10 in there as well since it's an active LTS until April 2020.

**Comment by ledsun** [comment]
It looks good.
But I do not have permission to set up travis ci.

**Comment by marocchino** [comment]
Screen Shot 2020-01-10 at 5 38 15
Sorry for the late response. I just activates travis for this repo but, It seems to need an event.
@ccarruitero Can you rebase it for test?

**Comment by ccarruitero** [comment]
@marocchino I just updated the branch to trigger the build

**Pull request merged**
